// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdrzavanjeVozila;

#nullable disable

namespace OdrzavanjeVozila.Migrations
{
    [DbContext(typeof(OdrzavanjeVozilaDbContext))]
    [Migration("20260506201106_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Automobil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojSasije")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumPrvogServisa")
                        .HasColumnType("datetime2");

                    b.Property<int>("Godiste")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistracijskiBroj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrenutnaKilometraza")
                        .HasColumnType("int");

                    b.Property<int>("VrstaPogona")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Automobili");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrojSasije = "WVWZZZ3CZ9E123456",
                            DatumPrvogServisa = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Godiste = 2019,
                            KorisnikId = 1,
                            Marka = "Volkswagen",
                            Model = "Golf",
                            RegistracijskiBroj = "ZG-234-AB",
                            TrenutnaKilometraza = 45000,
                            VrstaPogona = 0
                        },
                        new
                        {
                            Id = 2,
                            BrojSasije = "WBXYZ0000000000001",
                            DatumPrvogServisa = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Godiste = 2020,
                            KorisnikId = 2,
                            Marka = "BMW",
                            Model = "320",
                            RegistracijskiBroj = "ZG-567-CD",
                            TrenutnaKilometraza = 32000,
                            VrstaPogona = 1
                        });
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Dio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KatalogBroj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kategorija")
                        .HasColumnType("int");

                    b.Property<int>("KolicinaNaSkladistu")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proizvodac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dijelovi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cijena = 15.99m,
                            KatalogBroj = "OIL-001",
                            Kategorija = 0,
                            KolicinaNaSkladistu = 50,
                            Naziv = "Ulje motora",
                            Opis = "Sintetsko motorno ulje",
                            Proizvodac = "Castrol"
                        },
                        new
                        {
                            Id = 2,
                            Cijena = 25.50m,
                            KatalogBroj = "BRK-001",
                            Kategorija = 1,
                            KolicinaNaSkladistu = 30,
                            Naziv = "Kocione plocice",
                            Opis = "Set prednjih kocionih plocica",
                            Proizvodac = "Bosch"
                        });
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresa = "Ilica 200, Zagreb",
                            DatumRegistracije = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marko@mail.com",
                            Ime = "Marko",
                            Prezime = "Horvat",
                            Telefon = "099-1111111"
                        },
                        new
                        {
                            Id = 2,
                            Adresa = "Gunduliceva 50, Split",
                            DatumRegistracije = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ana@mail.com",
                            Ime = "Ana",
                            Prezime = "Novak",
                            Telefon = "099-2222222"
                        });
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Mehanicar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumZaposlenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RadionicaId")
                        .HasColumnType("int");

                    b.Property<decimal>("SatnicaEUR")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specijalizacija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RadionicaId");

                    b.ToTable("Mehanicari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumZaposlenja = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ime = "Petar",
                            Prezime = "Kovac",
                            RadionicaId = 1,
                            SatnicaEUR = 25.00m,
                            Specijalizacija = "Mehanika"
                        },
                        new
                        {
                            Id = 2,
                            DatumZaposlenja = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ime = "Jovan",
                            Prezime = "Jovanovic",
                            RadionicaId = 1,
                            SatnicaEUR = 30.00m,
                            Specijalizacija = "Elektrika"
                        },
                        new
                        {
                            Id = 3,
                            DatumZaposlenja = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ime = "Milan",
                            Prezime = "Milanovic",
                            RadionicaId = 2,
                            SatnicaEUR = 28.00m,
                            Specijalizacija = "Mehanika"
                        });
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.NalogStavka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CijenaKomad")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DioId")
                        .HasColumnType("int");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int>("NalogId")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DioId");

                    b.HasIndex("NalogId");

                    b.ToTable("NalogStavke");
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Radionica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Radionice");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresa = "Ilica 100, Zagreb",
                            Email = "info@radionica-zg.hr",
                            Naziv = "Radionica Zagreb",
                            Telefon = "01-1234567"
                        },
                        new
                        {
                            Id = 2,
                            Adresa = "Marmontova 50, Split",
                            Email = "info@radionica-split.hr",
                            Naziv = "Radionica Split",
                            Telefon = "021-1234567"
                        });
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.ServisniNalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutomobilId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumOtvaranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumZatvaranja")
                        .HasColumnType("datetime2");

                    b.Property<int>("KilometrazaPrilikomServisa")
                        .HasColumnType("int");

                    b.Property<int>("MehanicarId")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisRadova")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SljedecaPreporucenaPregleda")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UkupnaCijena")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AutomobilId");

                    b.HasIndex("MehanicarId");

                    b.ToTable("ServisniNalozi");
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Automobil", b =>
                {
                    b.HasOne("OdrzavanjeVozila.Klase.Korisnik", "Korisnik")
                        .WithMany("Vozila")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Mehanicar", b =>
                {
                    b.HasOne("OdrzavanjeVozila.Klase.Radionica", "Radionica")
                        .WithMany("Mehanicari")
                        .HasForeignKey("RadionicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Radionica");
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.NalogStavka", b =>
                {
                    b.HasOne("OdrzavanjeVozila.Klase.Dio", "Dio")
                        .WithMany("Stavke")
                        .HasForeignKey("DioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OdrzavanjeVozila.Klase.ServisniNalog", "Nalog")
                        .WithMany("Stavke")
                        .HasForeignKey("NalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dio");

                    b.Navigation("Nalog");
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.ServisniNalog", b =>
                {
                    b.HasOne("OdrzavanjeVozila.Klase.Automobil", "Automobil")
                        .WithMany("ServisniNalozi")
                        .HasForeignKey("AutomobilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OdrzavanjeVozila.Klase.Mehanicar", "Mehanicar")
                        .WithMany("Nalozi")
                        .HasForeignKey("MehanicarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Automobil");

                    b.Navigation("Mehanicar");
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Automobil", b =>
                {
                    b.Navigation("ServisniNalozi");
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Dio", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Korisnik", b =>
                {
                    b.Navigation("Vozila");
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Mehanicar", b =>
                {
                    b.Navigation("Nalozi");
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Radionica", b =>
                {
                    b.Navigation("Mehanicari");
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.ServisniNalog", b =>
                {
                    b.Navigation("Stavke");
                });
#pragma warning restore 612, 618
        }
    }
}
