// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdrzavanjeVozila;

#nullable disable

namespace OdrzavanjeVozila.Migrations
{
    [DbContext(typeof(OdrzavanjeVozilaDbContext))]
    [Migration("20260521162028_AddSoftDelete")]
    partial class AddSoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Automobil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojSasije")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DatumPrvogServisa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Godiste")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistracijskiBroj")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TrenutnaKilometraza")
                        .HasColumnType("int");

                    b.Property<int>("VrstaPogona")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrojSasije")
                        .IsUnique();

                    b.HasIndex("KorisnikId");

                    b.HasIndex("RegistracijskiBroj")
                        .IsUnique();

                    b.ToTable("Automobili");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrojSasije = "WVWZZZ3CZ9E123456",
                            DatumPrvogServisa = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Godiste = 2019,
                            KorisnikId = 1,
                            Marka = "Volkswagen",
                            Model = "Golf",
                            RegistracijskiBroj = "ZG-234-AB",
                            TrenutnaKilometraza = 45000,
                            VrstaPogona = 0
                        },
                        new
                        {
                            Id = 2,
                            BrojSasije = "WBXYZ0000000000001",
                            DatumPrvogServisa = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Godiste = 2020,
                            KorisnikId = 2,
                            Marka = "BMW",
                            Model = "320",
                            RegistracijskiBroj = "ZG-567-CD",
                            TrenutnaKilometraza = 32000,
                            VrstaPogona = 1
                        },
                        new
                        {
                            Id = 3,
                            BrojSasije = "W0L0AHL48J1234567",
                            DatumPrvogServisa = new DateTime(2024, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Godiste = 2018,
                            KorisnikId = 3,
                            Marka = "Opel",
                            Model = "Astra",
                            RegistracijskiBroj = "RI-345-EF",
                            TrenutnaKilometraza = 78000,
                            VrstaPogona = 4
                        },
                        new
                        {
                            Id = 4,
                            BrojSasije = "JTNB43BE003123456",
                            DatumPrvogServisa = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Godiste = 2021,
                            KorisnikId = 4,
                            Marka = "Toyota",
                            Model = "Corolla",
                            RegistracijskiBroj = "ZG-890-GH",
                            TrenutnaKilometraza = 21000,
                            VrstaPogona = 3
                        });
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Dio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("KatalogBroj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kategorija")
                        .HasColumnType("int");

                    b.Property<int>("KolicinaNaSkladistu")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proizvodac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dijelovi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cijena = 15.99m,
                            KatalogBroj = "OIL-001",
                            Kategorija = 0,
                            KolicinaNaSkladistu = 50,
                            Naziv = "Ulje motora",
                            Opis = "Sintetsko motorno ulje",
                            Proizvodac = "Castrol"
                        },
                        new
                        {
                            Id = 2,
                            Cijena = 25.50m,
                            KatalogBroj = "BRK-001",
                            Kategorija = 1,
                            KolicinaNaSkladistu = 30,
                            Naziv = "Kocione plocice",
                            Opis = "Set prednjih kocionih plocica",
                            Proizvodac = "Bosch"
                        },
                        new
                        {
                            Id = 3,
                            Cijena = 89.90m,
                            KatalogBroj = "BAT-014",
                            Kategorija = 3,
                            KolicinaNaSkladistu = 12,
                            Naziv = "Akumulator",
                            Opis = "Start-stop akumulator",
                            Proizvodac = "Varta"
                        },
                        new
                        {
                            Id = 4,
                            Cijena = 12.75m,
                            KatalogBroj = "FLT-022",
                            Kategorija = 0,
                            KolicinaNaSkladistu = 18,
                            Naziv = "Filter zraka",
                            Opis = "Motorni filter zraka",
                            Proizvodac = "Mann"
                        },
                        new
                        {
                            Id = 5,
                            Cijena = 79.99m,
                            KatalogBroj = "TIR-20555",
                            Kategorija = 5,
                            KolicinaNaSkladistu = 8,
                            Naziv = "Gume 205/55 R16",
                            Opis = "Ljetni komplet guma",
                            Proizvodac = "Michelin"
                        });
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresa = "Ilica 200, Zagreb",
                            DatumRegistracije = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marko.horvat@autosluzba.hr",
                            Ime = "Marko",
                            Prezime = "Horvat",
                            Telefon = "+385 91 482 1163"
                        },
                        new
                        {
                            Id = 2,
                            Adresa = "Gunduliceva 50, Split",
                            DatumRegistracije = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ana.novak@autosluzba.hr",
                            Ime = "Ana",
                            Prezime = "Novak",
                            Telefon = "+385 91 637 2048"
                        },
                        new
                        {
                            Id = 3,
                            Adresa = "Korzo 15, Rijeka",
                            DatumRegistracije = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivan.peric@autosluzba.hr",
                            Ime = "Ivan",
                            Prezime = "Peric",
                            Telefon = "+385 95 781 9044"
                        },
                        new
                        {
                            Id = 4,
                            Adresa = "Dubrovacka 21, Zagreb",
                            DatumRegistracije = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maja.juric@autosluzba.hr",
                            Ime = "Maja",
                            Prezime = "Juric",
                            Telefon = "+385 98 520 7712"
                        });
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Mehanicar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumZaposlenja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RadionicaId")
                        .HasColumnType("int");

                    b.Property<decimal>("SatnicaEUR")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specijalizacija")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RadionicaId");

                    b.HasIndex("Ime", "Prezime", "Specijalizacija", "RadionicaId")
                        .IsUnique();

                    b.ToTable("Mehanicari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumZaposlenja = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ime = "Petar",
                            Prezime = "Kovac",
                            RadionicaId = 1,
                            SatnicaEUR = 25.00m,
                            Specijalizacija = "Mehanika"
                        },
                        new
                        {
                            Id = 2,
                            DatumZaposlenja = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ime = "Jovan",
                            Prezime = "Jovanovic",
                            RadionicaId = 1,
                            SatnicaEUR = 30.00m,
                            Specijalizacija = "Elektrika"
                        },
                        new
                        {
                            Id = 3,
                            DatumZaposlenja = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ime = "Milan",
                            Prezime = "Milanovic",
                            RadionicaId = 2,
                            SatnicaEUR = 28.00m,
                            Specijalizacija = "Mehanika"
                        },
                        new
                        {
                            Id = 4,
                            DatumZaposlenja = new DateTime(2021, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ime = "Stjepan",
                            Prezime = "Boric",
                            RadionicaId = 3,
                            SatnicaEUR = 27.50m,
                            Specijalizacija = "Klimatizacija"
                        },
                        new
                        {
                            Id = 5,
                            DatumZaposlenja = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ime = "Filip",
                            Prezime = "Maric",
                            RadionicaId = 3,
                            SatnicaEUR = 32.00m,
                            Specijalizacija = "Dijagnostika"
                        });
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.NalogStavka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CijenaKomad")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DioId")
                        .HasColumnType("int");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int>("NalogId")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DioId");

                    b.HasIndex("NalogId");

                    b.ToTable("NalogStavke");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CijenaKomad = 15.99m,
                            DioId = 1,
                            Kolicina = 1,
                            NalogId = 1,
                            Napomena = "Motorno ulje 5W-30"
                        },
                        new
                        {
                            Id = 2,
                            CijenaKomad = 25.50m,
                            DioId = 2,
                            Kolicina = 4,
                            NalogId = 1,
                            Napomena = "Prednji set kočionih pločica"
                        },
                        new
                        {
                            Id = 3,
                            CijenaKomad = 89.90m,
                            DioId = 3,
                            Kolicina = 1,
                            NalogId = 2,
                            Napomena = "Start-stop akumulator"
                        },
                        new
                        {
                            Id = 4,
                            CijenaKomad = 12.75m,
                            DioId = 4,
                            Kolicina = 2,
                            NalogId = 3,
                            Napomena = "Filteri za zrak"
                        },
                        new
                        {
                            Id = 5,
                            CijenaKomad = 79.99m,
                            DioId = 5,
                            Kolicina = 4,
                            NalogId = 4,
                            Napomena = "Set ljetnih guma"
                        });
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Radionica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Naziv", "Adresa")
                        .IsUnique();

                    b.ToTable("Radionice");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresa = "Ilica 100, Zagreb",
                            Email = "kontakt.zagreb@radionica-mreza.hr",
                            Naziv = "Radionica Zagreb",
                            Telefon = "+385 1 4829 615"
                        },
                        new
                        {
                            Id = 2,
                            Adresa = "Marmontova 50, Split",
                            Email = "kontakt.split@radionica-mreza.hr",
                            Naziv = "Radionica Split",
                            Telefon = "+385 21 784 392"
                        },
                        new
                        {
                            Id = 3,
                            Adresa = "Riva 12, Rijeka",
                            Email = "kontakt.rijeka@radionica-mreza.hr",
                            Naziv = "Radionica Rijeka",
                            Telefon = "+385 51 642 880"
                        });
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.ServisniNalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutomobilId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumOtvaranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumZatvaranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("KilometrazaPrilikomServisa")
                        .HasColumnType("int");

                    b.Property<int>("MehanicarId")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisRadova")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SljedecaPreporucenaPregleda")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UkupnaCijena")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AutomobilId");

                    b.HasIndex("MehanicarId");

                    b.ToTable("ServisniNalozi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutomobilId = 1,
                            DatumOtvaranja = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumZatvaranja = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KilometrazaPrilikomServisa = 45250,
                            MehanicarId = 1,
                            Napomena = "Vozilo uredno, preporucena kontrola za 6 mjeseci",
                            OpisRadova = "Redovni servis i zamjena ulja",
                            SljedecaPreporucenaPregleda = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            UkupnaCijena = 96.97m
                        },
                        new
                        {
                            Id = 2,
                            AutomobilId = 2,
                            DatumOtvaranja = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KilometrazaPrilikomServisa = 32220,
                            MehanicarId = 2,
                            Napomena = "Čeka potvrdu narudžbe dodatnog dijela",
                            OpisRadova = "Dijagnostika elektrike i zamjena akumulatora",
                            SljedecaPreporucenaPregleda = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            UkupnaCijena = 89.90m
                        },
                        new
                        {
                            Id = 3,
                            AutomobilId = 3,
                            DatumOtvaranja = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumZatvaranja = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KilometrazaPrilikomServisa = 78120,
                            MehanicarId = 3,
                            Napomena = "Kočnice testirane i ispravne",
                            OpisRadova = "Servis kočnica i zamjena plocica",
                            SljedecaPreporucenaPregleda = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            UkupnaCijena = 112.45m
                        },
                        new
                        {
                            Id = 4,
                            AutomobilId = 4,
                            DatumOtvaranja = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KilometrazaPrilikomServisa = 21400,
                            MehanicarId = 4,
                            Napomena = "Čeka dolazak vozila u radionicu",
                            OpisRadova = "Zamjena guma i sezonski pregled",
                            Status = 0,
                            UkupnaCijena = 79.99m
                        });
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Automobil", b =>
                {
                    b.HasOne("OdrzavanjeVozila.Klase.Korisnik", "Korisnik")
                        .WithMany("Vozila")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Mehanicar", b =>
                {
                    b.HasOne("OdrzavanjeVozila.Klase.Radionica", "Radionica")
                        .WithMany("Mehanicari")
                        .HasForeignKey("RadionicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Radionica");
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.NalogStavka", b =>
                {
                    b.HasOne("OdrzavanjeVozila.Klase.Dio", "Dio")
                        .WithMany("Stavke")
                        .HasForeignKey("DioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OdrzavanjeVozila.Klase.ServisniNalog", "Nalog")
                        .WithMany("Stavke")
                        .HasForeignKey("NalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dio");

                    b.Navigation("Nalog");
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.ServisniNalog", b =>
                {
                    b.HasOne("OdrzavanjeVozila.Klase.Automobil", "Automobil")
                        .WithMany("ServisniNalozi")
                        .HasForeignKey("AutomobilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OdrzavanjeVozila.Klase.Mehanicar", "Mehanicar")
                        .WithMany("Nalozi")
                        .HasForeignKey("MehanicarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Automobil");

                    b.Navigation("Mehanicar");
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Automobil", b =>
                {
                    b.Navigation("ServisniNalozi");
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Dio", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Korisnik", b =>
                {
                    b.Navigation("Vozila");
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Mehanicar", b =>
                {
                    b.Navigation("Nalozi");
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.Radionica", b =>
                {
                    b.Navigation("Mehanicari");
                });

            modelBuilder.Entity("OdrzavanjeVozila.Klase.ServisniNalog", b =>
                {
                    b.Navigation("Stavke");
                });
#pragma warning restore 612, 618
        }
    }
}
