// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using OdrzavanjeVozila;

#nullable disable

namespace OdrzavanjeVozila.Migrations
{
    [DbContext(typeof(OdrzavanjeVozilaDbContext))]
    [Migration("20260518160000_AddMoreSeedData")]
    partial class AddMoreSeedData
    {
    }
}
